---
# tasks file for s3-role
- name: list buckets
  include_tasks: "create_bucket.yml"
  when: create_bucket | default(False)

- name: list buckets
  include_tasks: "bucket_details.yml"
  when: bucket_details | default(False)

